-- GA4 for Guest Portal + Audience.
--
-- The Snowflake Connector for Google Analytics (aggregate) writes ONE view per
-- report/grain into its destination schema:
--     GOOGLE_ANALYTICS_AGGREGATE_DATA_DEST_DB.GOOGLE_ANALYTICS_AGGREGATE_DATA_DEST_SCHEMA
-- named {report}_GA4_{GRAIN}, e.g. for Abbaye (report base "ABBAYE_PARIS"):
--     ABBAYE_PARIS_GA4_DAILY      date, sessionSource, hostName, sessions, activeUsers,
--                                 totalUsers, newUsers, screenPageViews, engagedSessions,
--                                 userEngagementDuration*, keyEvents*
--     ABBAYE_PARIS_GA4_EVENTS     date, eventName, sessionSource, hostName, sessions,
--                                 eventCount, keyEvents*
--     ABBAYE_PARIS_GA4_ITEMS      date, itemName, itemsViewed, itemsPurchased
--     ABBAYE_PARIS_GA4_DEVICE     date, deviceCategory, hostName, sessions
--     ABBAYE_PARIS_GA4_LOCATION   date, city, country, region, sessionSource, hostName,
--                                 sessions, keyEvents*
--     ABBAYE_PARIS_GA4_SLIDES     date, eventName, linkUrl, linkText, eventCount
--   (* keyEvents / userEngagementDuration arrive as VARCHAR — the app coerces them.)
--
-- The app reads these per-grain views DIRECTLY (no union table required). Point a
-- customer at them via DASHBOARD_CUSTOMERS.GA4_CONFIG (see sql/01_control_tables.sql):
--     {"database":"GOOGLE_ANALYTICS_AGGREGATE_DATA_DEST_DB",
--      "schema":"GOOGLE_ANALYTICS_AGGREGATE_DATA_DEST_SCHEMA",
--      "report":"ABBAYE_PARIS"}
--
-- Grant the app's role read access to the connector schema:
--   GRANT USAGE ON DATABASE GOOGLE_ANALYTICS_AGGREGATE_DATA_DEST_DB TO ROLE <app_role>;
--   GRANT USAGE ON SCHEMA   GOOGLE_ANALYTICS_AGGREGATE_DATA_DEST_DB.GOOGLE_ANALYTICS_AGGREGATE_DATA_DEST_SCHEMA TO ROLE <app_role>;
--   GRANT SELECT ON ALL VIEWS IN SCHEMA GOOGLE_ANALYTICS_AGGREGATE_DATA_DEST_DB.GOOGLE_ANALYTICS_AGGREGATE_DATA_DEST_SCHEMA TO ROLE <app_role>;
--
-- ---------------------------------------------------------------------------
-- OPTIONAL convenience union (NOT used by the app) — a single REPORT-tagged long
-- view, handy for ad-hoc SQL/BI. Adjust the report base per client.
-- ---------------------------------------------------------------------------
CREATE OR REPLACE VIEW SALES_ANALYTICS.PUBLIC.ABBAYE_GA4 AS
SELECT 'items' AS REPORT, DATE, ITEMNAME AS ITEM_NAME, NULL AS EVENT_NAME, NULL AS DEVICE_CATEGORY,
       NULL AS CITY, NULL AS COUNTRY, NULL AS REGION, NULL AS LINK_URL, NULL AS LINK_TEXT,
       NULL AS SESSION_SOURCE, NULL AS HOST_NAME,
       NULL AS SESSIONS, NULL AS KEY_EVENTS, ITEMSVIEWED AS ITEMS_VIEWED, ITEMSPURCHASED AS ITEMS_PURCHASED,
       NULL AS EVENT_COUNT, NULL AS ACTIVE_USERS, NULL AS TOTAL_USERS, NULL AS NEW_USERS,
       NULL AS SCREEN_PAGE_VIEWS, NULL AS ENGAGED_SESSIONS, NULL AS USER_ENGAGEMENT_DURATION
FROM GOOGLE_ANALYTICS_AGGREGATE_DATA_DEST_DB.GOOGLE_ANALYTICS_AGGREGATE_DATA_DEST_SCHEMA.ABBAYE_PARIS_GA4_ITEMS
UNION ALL
SELECT 'events', DATE, NULL, EVENTNAME, NULL, NULL, NULL, NULL, NULL, NULL,
       SESSIONSOURCE, HOSTNAME,
       SESSIONS, TRY_TO_NUMBER(KEYEVENTS), NULL, NULL,
       EVENTCOUNT, NULL, NULL, NULL, NULL, NULL, NULL
FROM GOOGLE_ANALYTICS_AGGREGATE_DATA_DEST_DB.GOOGLE_ANALYTICS_AGGREGATE_DATA_DEST_SCHEMA.ABBAYE_PARIS_GA4_EVENTS
UNION ALL
SELECT 'daily', DATE, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
       SESSIONSOURCE, HOSTNAME,
       SESSIONS, TRY_TO_NUMBER(KEYEVENTS), NULL, NULL,
       NULL, ACTIVEUSERS, TOTALUSERS, NEWUSERS,
       SCREENPAGEVIEWS, ENGAGEDSESSIONS, TRY_TO_NUMBER(USERENGAGEMENTDURATION)
FROM GOOGLE_ANALYTICS_AGGREGATE_DATA_DEST_DB.GOOGLE_ANALYTICS_AGGREGATE_DATA_DEST_SCHEMA.ABBAYE_PARIS_GA4_DAILY
UNION ALL
SELECT 'device', DATE, NULL, NULL, DEVICECATEGORY, NULL, NULL, NULL, NULL, NULL,
       NULL, HOSTNAME,
       SESSIONS, NULL, NULL, NULL,
       NULL, NULL, NULL, NULL, NULL, NULL, NULL
FROM GOOGLE_ANALYTICS_AGGREGATE_DATA_DEST_DB.GOOGLE_ANALYTICS_AGGREGATE_DATA_DEST_SCHEMA.ABBAYE_PARIS_GA4_DEVICE
UNION ALL
SELECT 'location', DATE, NULL, NULL, NULL, CITY, COUNTRY, REGION, NULL, NULL,
       SESSIONSOURCE, HOSTNAME,
       SESSIONS, TRY_TO_NUMBER(KEYEVENTS), NULL, NULL,
       NULL, NULL, NULL, NULL, NULL, NULL, NULL
FROM GOOGLE_ANALYTICS_AGGREGATE_DATA_DEST_DB.GOOGLE_ANALYTICS_AGGREGATE_DATA_DEST_SCHEMA.ABBAYE_PARIS_GA4_LOCATION
UNION ALL
SELECT 'slides', DATE, NULL, EVENTNAME, NULL, NULL, NULL, NULL, LINKURL, LINKTEXT,
       NULL, NULL, NULL, NULL, NULL, NULL,
       EVENTCOUNT, NULL, NULL, NULL, NULL, NULL, NULL
FROM GOOGLE_ANALYTICS_AGGREGATE_DATA_DEST_DB.GOOGLE_ANALYTICS_AGGREGATE_DATA_DEST_SCHEMA.ABBAYE_PARIS_GA4_SLIDES;
